### ISSUE TITLE
HTTPS support

### ISSUE THREAD

**Issue by tom-butler** [infracoders/infracoders.github.com#30]
Github now supports custom custom certificates, can we please enable this for infrastructurecoders.com?

**Comment by dlutzy** [comment]
Thank you for the suggestion. Yes that seems like a good thing to do.  We'll follow it up.

**Comment by dlutzy** [comment]
This has been resolved :-)
https://infrastructurecoders.com/
If you have additional suggestions for the site feel free to fork and make a pull request.
